server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          default-label: master
          uri: https://github.com/dejanjanjic/report-incident-config-server.git
          searchPaths:
            - incident-service
            - moderation-service
            - auth-service
            - alert-service
            - api-gateway
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
